spring.application.name=landing
spring.datasource.url=jdbc:mysql://localhost:3306/technerd
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false